set_property PACKAGE_PIN L21 [get_ports I2C_SDA]

set_property IOSTANDARD LVCMOS25 [get_ports GMII_COL]
set_property IOSTANDARD LVCMOS25 [get_ports GMII_CRS]
set_property IOSTANDARD LVCMOS25 [get_ports GMII_GTXCLK]
set_property IOSTANDARD LVCMOS25 [get_ports GMII_MDC]
set_property IOSTANDARD LVCMOS25 [get_ports GMII_MDIO]
set_property IOSTANDARD LVCMOS25 [get_ports GMII_RSTn]
set_property IOSTANDARD LVCMOS25 [get_ports {GMII_RXD[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GMII_RXD[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GMII_RXD[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GMII_RXD[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GMII_RXD[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GMII_RXD[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GMII_RXD[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GMII_RXD[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports GMII_RX_CLK]
set_property IOSTANDARD LVCMOS25 [get_ports GMII_RX_DV]
set_property IOSTANDARD LVCMOS25 [get_ports GMII_RX_ER]
set_property IOSTANDARD LVCMOS25 [get_ports {GMII_TXD[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GMII_TXD[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GMII_TXD[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GMII_TXD[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GMII_TXD[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GMII_TXD[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GMII_TXD[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GMII_TXD[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports GMII_TX_CLK]
set_property IOSTANDARD LVCMOS25 [get_ports GMII_TX_EN]
set_property IOSTANDARD LVCMOS25 [get_ports GMII_TX_ER]
set_property IOSTANDARD LVCMOS25 [get_ports I2C_SDA]
set_property IOSTANDARD LVCMOS25 [get_ports I2C_SCL]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_SWITCH[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_SWITCH[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_SWITCH[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_SWITCH[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports GPIO_SMA_IN]
set_property IOSTANDARD LVCMOS25 [get_ports GPIO_SMA_OUT]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_LED[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_LED[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_LED[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_LED[3]}]
set_property IOSTANDARD LVCMOS15 [get_ports SW_N]
set_property IOSTANDARD LVDS [get_ports SYSCLK_200MP_IN]
set_property IOSTANDARD LVDS [get_ports SYSCLK_200MN_IN]


set_property PACKAGE_PIN AD12 [get_ports SYSCLK_200MP_IN]
set_property PACKAGE_PIN AD11 [get_ports SYSCLK_200MN_IN]
set_property PACKAGE_PIN L20 [get_ports GMII_RSTn]
set_property PACKAGE_PIN M27 [get_ports GMII_TX_EN]
set_property PACKAGE_PIN N27 [get_ports {GMII_TXD[0]}]
set_property PACKAGE_PIN N25 [get_ports {GMII_TXD[1]}]
set_property PACKAGE_PIN M29 [get_ports {GMII_TXD[2]}]
set_property PACKAGE_PIN L28 [get_ports {GMII_TXD[3]}]
set_property PACKAGE_PIN J26 [get_ports {GMII_TXD[4]}]
set_property PACKAGE_PIN K26 [get_ports {GMII_TXD[5]}]
set_property PACKAGE_PIN L30 [get_ports {GMII_TXD[6]}]
set_property PACKAGE_PIN J28 [get_ports {GMII_TXD[7]}]
set_property PACKAGE_PIN N29 [get_ports GMII_TX_ER]
set_property PACKAGE_PIN U27 [get_ports GMII_RX_CLK]
set_property PACKAGE_PIN R28 [get_ports GMII_RX_DV]
set_property PACKAGE_PIN U30 [get_ports {GMII_RXD[0]}]
set_property PACKAGE_PIN U25 [get_ports {GMII_RXD[1]}]
set_property PACKAGE_PIN T25 [get_ports {GMII_RXD[2]}]
set_property PACKAGE_PIN U28 [get_ports {GMII_RXD[3]}]
set_property PACKAGE_PIN R19 [get_ports {GMII_RXD[4]}]
set_property PACKAGE_PIN T27 [get_ports {GMII_RXD[5]}]
set_property PACKAGE_PIN T26 [get_ports {GMII_RXD[6]}]
set_property PACKAGE_PIN T28 [get_ports {GMII_RXD[7]}]
set_property PACKAGE_PIN V26 [get_ports GMII_RX_ER]
set_property PACKAGE_PIN R30 [get_ports GMII_CRS]
set_property PACKAGE_PIN W19 [get_ports GMII_COL]
set_property PACKAGE_PIN J21 [get_ports GMII_MDIO]
set_property PACKAGE_PIN K30 [get_ports GMII_GTXCLK]
set_property PACKAGE_PIN M28 [get_ports GMII_TX_CLK]
set_property PACKAGE_PIN R23 [get_ports GMII_MDC]
set_property PACKAGE_PIN K21 [get_ports I2C_SCL]
set_property PACKAGE_PIN Y29 [get_ports {GPIO_SWITCH[0]}]
set_property PACKAGE_PIN W29 [get_ports {GPIO_SWITCH[1]}]
set_property PACKAGE_PIN AA28 [get_ports {GPIO_SWITCH[2]}]
set_property PACKAGE_PIN Y28 [get_ports {GPIO_SWITCH[3]}]
set_property PACKAGE_PIN Y23 [get_ports GPIO_SMA_IN]
set_property PACKAGE_PIN Y24 [get_ports GPIO_SMA_OUT]
set_property PACKAGE_PIN AE26 [get_ports {GPIO_LED[0]}]
set_property PACKAGE_PIN G19 [get_ports {GPIO_LED[1]}]
set_property PACKAGE_PIN E18 [get_ports {GPIO_LED[2]}]
set_property PACKAGE_PIN F16 [get_ports {GPIO_LED[3]}]
set_property PACKAGE_PIN AA12 [get_ports SW_N]

create_clock -period 5.000 -name SYSCLK_200MP_IN -waveform {0.000 2.500} [get_ports SYSCLK_200MP_IN]
create_clock -period 40.000 -name GMII_TX_CLK -waveform {0.000 20.000} [get_ports GMII_TX_CLK]
create_clock -period 8.000 -name GMII_RX_CLK -waveform {0.000 4.000} [get_ports GMII_RX_CLK]
set_clock_groups -logically_exclusive -group [get_clocks GMII_TX_CLK] -group [get_clocks CLK_125M]


set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 6 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]




set_property IOB FALSE [get_cells -hierarchical -filter {name =~ */GMII_RXCNT/IOB_RD_*}]
set_property IOB FALSE [get_cells -hierarchical -filter {name =~ */GMII_RXCNT/IOB_RDV}]
set_property IOB FALSE [get_cells -hierarchical -filter {name =~ */GMII_RXCNT/IOB_RERR}]

set_input_delay -clock [get_clocks GMII_RX_CLK] -min 0.500 [get_ports GMII_RXD*]
set_input_delay -clock [get_clocks GMII_RX_CLK] -min 0.500 [get_ports GMII_RX_ER]
set_input_delay -clock [get_clocks GMII_RX_CLK] -min 0.500 [get_ports GMII_RX_DV]
set_input_delay -clock [get_clocks GMII_RX_CLK] -max 5.500 [get_ports GMII_RXD*]
set_input_delay -clock [get_clocks GMII_RX_CLK] -max 5.500 [get_ports GMII_RX_ER]
set_input_delay -clock [get_clocks GMII_RX_CLK] -max 5.500 [get_ports GMII_RX_DV]

set_max_delay -from [get_ports GMII_MDIO] 10.000
set_min_delay -from [get_ports GMII_MDIO] 0.000
set_max_delay -from [get_ports I2C_SDA] 10.000
set_min_delay -from [get_ports I2C_SDA] 0.000

set_property IOB TRUE [get_cells -hierarchical -filter {name =~ */GMII_TXCNT/IOB_TD_*}]
set_property IOB TRUE [get_cells -hierarchical -filter {name =~ */GMII_TXCNT/IOB_TEN}]

set_max_delay -from [get_clocks GMII_TX_CLK] -to [get_ports GMII_TXD*] 30.000
set_min_delay -from [get_clocks GMII_TX_CLK] -to [get_ports GMII_TXD*] 0.000
set_max_delay -from [get_clocks GMII_TX_CLK] -to [get_ports GMII_TX_EN] 30.000
set_min_delay -from [get_clocks GMII_TX_CLK] -to [get_ports GMII_TX_EN] 0.000
set_max_delay -from [get_clocks GMII_TX_CLK] -to [get_ports GMII_TX_ER] 30.000
set_min_delay -from [get_clocks GMII_TX_CLK] -to [get_ports GMII_TX_ER] 0.000


set_max_delay -datapath_only -from [get_clocks CLK_125M] -to [get_ports GMII_GTXCLK] 3.200
set_max_delay -datapath_only -from [get_clocks CLK_125M] -to [get_ports GMII_TX_EN] 3.200
set_max_delay -datapath_only -from [get_clocks CLK_125M] -to [get_ports GMII_TXD*] 3.200
set_max_delay -datapath_only -from [get_clocks CLK_125M] -to [get_ports GMII_TX_ER] 3.200

set_max_delay -datapath_only -from [get_clocks SYSCLK_200MP_IN] -to [get_ports GMII_MDC] 10.000
set_max_delay -datapath_only -from [get_clocks SYSCLK_200MP_IN] -to [get_ports GMII_MDIO] 10.000
set_max_delay -datapath_only -from [get_clocks SYSCLK_200MP_IN] -to [get_ports GMII_RSTn] 10.000
set_max_delay -datapath_only -from [get_clocks SYSCLK_200MP_IN] -to [get_ports I2C_SCL] 10.000
set_max_delay -datapath_only -from [get_clocks SYSCLK_200MP_IN] -to [get_ports I2C_SDA] 10.000



set_property IOSTANDARD LVDS_25 [get_ports LA_HPC_P*]
set_property IOSTANDARD LVDS_25 [get_ports LA_HPC_N*]
set_property IOSTANDARD LVDS_25 [get_ports HA_HPC_P*]
set_property IOSTANDARD LVDS_25 [get_ports HA_HPC_N*]
set_property IOSTANDARD LVDS_25 [get_ports LA_LPC_P*]
set_property IOSTANDARD LVDS_25 [get_ports LA_LPC_N*]

#set_property IOSTANDARD LVDS_25 [get_ports FMC_DEBUGOUT_P*]
#set_property IOSTANDARD LVDS_25 [get_ports FMC_DEBUGOUT_N*]

set_property PACKAGE_PIN G22 [get_ports {LA_HPC_P[31]}]
set_property PACKAGE_PIN F22 [get_ports {LA_HPC_N[31]}]
set_property PACKAGE_PIN D22 [get_ports {LA_HPC_P[30]}]
set_property PACKAGE_PIN C22 [get_ports {LA_HPC_N[30]}]
set_property PACKAGE_PIN C17 [get_ports {LA_HPC_P[29]}]
set_property PACKAGE_PIN B17 [get_ports {LA_HPC_N[29]}]
set_property PACKAGE_PIN D16 [get_ports {LA_HPC_P[28]}]
set_property PACKAGE_PIN C16 [get_ports {LA_HPC_N[28]}]
set_property PACKAGE_PIN C19 [get_ports {LA_HPC_P[27]}]
set_property PACKAGE_PIN B19 [get_ports {LA_HPC_N[27]}]
set_property PACKAGE_PIN B18 [get_ports {LA_HPC_P[26]}]
set_property PACKAGE_PIN A18 [get_ports {LA_HPC_N[26]}]
set_property PACKAGE_PIN G17 [get_ports {LA_HPC_P[25]}]
set_property PACKAGE_PIN F17 [get_ports {LA_HPC_N[25]}]
set_property PACKAGE_PIN A16 [get_ports {LA_HPC_P[24]}]
set_property PACKAGE_PIN A17 [get_ports {LA_HPC_N[24]}]
set_property PACKAGE_PIN B22 [get_ports {LA_HPC_P[23]}]
set_property PACKAGE_PIN A22 [get_ports {LA_HPC_N[23]}]
set_property PACKAGE_PIN C20 [get_ports {LA_HPC_P[22]}]
set_property PACKAGE_PIN B20 [get_ports {LA_HPC_N[22]}]
set_property PACKAGE_PIN A20 [get_ports {LA_HPC_P[21]}]
set_property PACKAGE_PIN A21 [get_ports {LA_HPC_N[21]}]
set_property PACKAGE_PIN E19 [get_ports {LA_HPC_P[20]}]
set_property PACKAGE_PIN D19 [get_ports {LA_HPC_N[20]}]
set_property PACKAGE_PIN G18 [get_ports {LA_HPC_P[19]}]
set_property PACKAGE_PIN F18 [get_ports {LA_HPC_N[19]}]
set_property PACKAGE_PIN F21 [get_ports {LA_HPC_P[18]}]
set_property PACKAGE_PIN E21 [get_ports {LA_HPC_N[18]}]
set_property PACKAGE_PIN F20 [get_ports {LA_HPC_P[17]}]
set_property PACKAGE_PIN E20 [get_ports {LA_HPC_N[17]}]
set_property PACKAGE_PIN B27 [get_ports {LA_HPC_P[16]}]
set_property PACKAGE_PIN A27 [get_ports {LA_HPC_N[16]}]
set_property PACKAGE_PIN C24 [get_ports {LA_HPC_P[15]}]
set_property PACKAGE_PIN B24 [get_ports {LA_HPC_N[15]}]
set_property PACKAGE_PIN B28 [get_ports {LA_HPC_P[14]}]
set_property PACKAGE_PIN A28 [get_ports {LA_HPC_N[14]}]
set_property PACKAGE_PIN A25 [get_ports {LA_HPC_P[13]}]
set_property PACKAGE_PIN A26 [get_ports {LA_HPC_N[13]}]
set_property PACKAGE_PIN C29 [get_ports {LA_HPC_P[12]}]
set_property PACKAGE_PIN B29 [get_ports {LA_HPC_N[12]}]
set_property PACKAGE_PIN G27 [get_ports {LA_HPC_P[11]}]
set_property PACKAGE_PIN F27 [get_ports {LA_HPC_N[11]}]
set_property PACKAGE_PIN D29 [get_ports {LA_HPC_P[10]}]
set_property PACKAGE_PIN C30 [get_ports {LA_HPC_N[10]}]
set_property PACKAGE_PIN B30 [get_ports {LA_HPC_P[9]}]
set_property PACKAGE_PIN A30 [get_ports {LA_HPC_N[9]}]
set_property PACKAGE_PIN E29 [get_ports {LA_HPC_P[8]}]
set_property PACKAGE_PIN E30 [get_ports {LA_HPC_N[8]}]
set_property PACKAGE_PIN E28 [get_ports {LA_HPC_P[7]}]
set_property PACKAGE_PIN D28 [get_ports {LA_HPC_N[7]}]
set_property PACKAGE_PIN H30 [get_ports {LA_HPC_P[6]}]
set_property PACKAGE_PIN G30 [get_ports {LA_HPC_N[6]}]
set_property PACKAGE_PIN G29 [get_ports {LA_HPC_P[5]}]
set_property PACKAGE_PIN F30 [get_ports {LA_HPC_N[5]}]
set_property PACKAGE_PIN G28 [get_ports {LA_HPC_P[4]}]
set_property PACKAGE_PIN F28 [get_ports {LA_HPC_N[4]}]
set_property PACKAGE_PIN H26 [get_ports {LA_HPC_P[3]}]
set_property PACKAGE_PIN H27 [get_ports {LA_HPC_N[3]}]
set_property PACKAGE_PIN H24 [get_ports {LA_HPC_P[2]}]
set_property PACKAGE_PIN H25 [get_ports {LA_HPC_N[2]}]
set_property PACKAGE_PIN D26 [get_ports {LA_HPC_P[1]}]
set_property PACKAGE_PIN C26 [get_ports {LA_HPC_N[1]}]
set_property PACKAGE_PIN C25 [get_ports {LA_HPC_P[0]}]
set_property PACKAGE_PIN B25 [get_ports {LA_HPC_N[0]}]

set_property PACKAGE_PIN H11 [get_ports {HA_HPC_P[19]}]
set_property PACKAGE_PIN H12 [get_ports {HA_HPC_N[19]}]
set_property PACKAGE_PIN K14 [get_ports {HA_HPC_P[18]}]
set_property PACKAGE_PIN J14 [get_ports {HA_HPC_N[18]}]
set_property PACKAGE_PIN G13 [get_ports {HA_HPC_P[17]}]
set_property PACKAGE_PIN F13 [get_ports {HA_HPC_N[17]}]
set_property PACKAGE_PIN L15 [get_ports {HA_HPC_P[16]}]
set_property PACKAGE_PIN K15 [get_ports {HA_HPC_N[16]}]
set_property PACKAGE_PIN H15 [get_ports {HA_HPC_P[15]}]
set_property PACKAGE_PIN G15 [get_ports {HA_HPC_N[15]}]
set_property PACKAGE_PIN J16 [get_ports {HA_HPC_P[14]}]
set_property PACKAGE_PIN H16 [get_ports {HA_HPC_N[14]}]
set_property PACKAGE_PIN L16 [get_ports {HA_HPC_P[13]}]
set_property PACKAGE_PIN K16 [get_ports {HA_HPC_N[13]}]
set_property PACKAGE_PIN C15 [get_ports {HA_HPC_P[12]}]
set_property PACKAGE_PIN B15 [get_ports {HA_HPC_N[12]}]
set_property PACKAGE_PIN B13 [get_ports {HA_HPC_P[11]}]
set_property PACKAGE_PIN A13 [get_ports {HA_HPC_N[11]}]
set_property PACKAGE_PIN A11 [get_ports {HA_HPC_P[10]}]
set_property PACKAGE_PIN A12 [get_ports {HA_HPC_N[10]}]
set_property PACKAGE_PIN F12 [get_ports {HA_HPC_P[9]}]
set_property PACKAGE_PIN E13 [get_ports {HA_HPC_N[9]}]
set_property PACKAGE_PIN E14 [get_ports {HA_HPC_P[8]}]
set_property PACKAGE_PIN E15 [get_ports {HA_HPC_N[8]}]
set_property PACKAGE_PIN B14 [get_ports {HA_HPC_P[7]}]
set_property PACKAGE_PIN A15 [get_ports {HA_HPC_N[7]}]
set_property PACKAGE_PIN D14 [get_ports {HA_HPC_P[6]}]
set_property PACKAGE_PIN C14 [get_ports {HA_HPC_N[6]}]
set_property PACKAGE_PIN F15 [get_ports {HA_HPC_P[5]}]
set_property PACKAGE_PIN E16 [get_ports {HA_HPC_N[5]}]
set_property PACKAGE_PIN F11 [get_ports {HA_HPC_P[4]}]
set_property PACKAGE_PIN E11 [get_ports {HA_HPC_N[4]}]
set_property PACKAGE_PIN C12 [get_ports {HA_HPC_P[3]}]
set_property PACKAGE_PIN B12 [get_ports {HA_HPC_N[3]}]
set_property PACKAGE_PIN D11 [get_ports {HA_HPC_P[2]}]
set_property PACKAGE_PIN C11 [get_ports {HA_HPC_N[2]}]
set_property PACKAGE_PIN H14 [get_ports {HA_HPC_P[1]}]
set_property PACKAGE_PIN G14 [get_ports {HA_HPC_N[1]}]
set_property PACKAGE_PIN D12 [get_ports {HA_HPC_P[0]}]
set_property PACKAGE_PIN D13 [get_ports {HA_HPC_N[0]}]


set_property PACKAGE_PIN AD29 [get_ports {LA_LPC_P[31]}]
set_property PACKAGE_PIN AE29 [get_ports {LA_LPC_N[31]}]
set_property PACKAGE_PIN AB29 [get_ports {LA_LPC_P[30]}]
set_property PACKAGE_PIN AB30 [get_ports {LA_LPC_N[30]}]
set_property PACKAGE_PIN AE28 [get_ports {LA_LPC_P[29]}]
set_property PACKAGE_PIN AF28 [get_ports {LA_LPC_N[29]}]
set_property PACKAGE_PIN AE30 [get_ports {LA_LPC_P[28]}]
set_property PACKAGE_PIN AF30 [get_ports {LA_LPC_N[28]}]
set_property PACKAGE_PIN AJ28 [get_ports {LA_LPC_P[27]}]
set_property PACKAGE_PIN AJ29 [get_ports {LA_LPC_N[27]}]
set_property PACKAGE_PIN AK29 [get_ports {LA_LPC_P[26]}]
set_property PACKAGE_PIN AK30 [get_ports {LA_LPC_N[26]}]
set_property PACKAGE_PIN AC26 [get_ports {LA_LPC_P[25]}]
set_property PACKAGE_PIN AD26 [get_ports {LA_LPC_N[25]}]
set_property PACKAGE_PIN AG30 [get_ports {LA_LPC_P[24]}]
set_property PACKAGE_PIN AH30 [get_ports {LA_LPC_N[24]}]
set_property PACKAGE_PIN AH26 [get_ports {LA_LPC_P[23]}]
set_property PACKAGE_PIN AH27 [get_ports {LA_LPC_N[23]}]
set_property PACKAGE_PIN AJ27 [get_ports {LA_LPC_P[22]}]
set_property PACKAGE_PIN AK28 [get_ports {LA_LPC_N[22]}]
set_property PACKAGE_PIN AG27 [get_ports {LA_LPC_P[21]}]
set_property PACKAGE_PIN AG28 [get_ports {LA_LPC_N[21]}]
set_property PACKAGE_PIN AF26 [get_ports {LA_LPC_P[20]}]
set_property PACKAGE_PIN AF27 [get_ports {LA_LPC_N[20]}]
set_property PACKAGE_PIN AJ26 [get_ports {LA_LPC_P[19]}]
set_property PACKAGE_PIN AK26 [get_ports {LA_LPC_N[19]}]
set_property PACKAGE_PIN AD27 [get_ports {LA_LPC_P[18]}]
set_property PACKAGE_PIN AD28 [get_ports {LA_LPC_N[18]}]
set_property PACKAGE_PIN AB27 [get_ports {LA_LPC_P[17]}]
set_property PACKAGE_PIN AC27 [get_ports {LA_LPC_N[17]}]
set_property PACKAGE_PIN AC22 [get_ports {LA_LPC_P[16]}]
set_property PACKAGE_PIN AD22 [get_ports {LA_LPC_N[16]}]
set_property PACKAGE_PIN AC24 [get_ports {LA_LPC_P[15]}]
set_property PACKAGE_PIN AD24 [get_ports {LA_LPC_N[15]}]
set_property PACKAGE_PIN AD21 [get_ports {LA_LPC_P[14]}]
set_property PACKAGE_PIN AE21 [get_ports {LA_LPC_N[14]}]
set_property PACKAGE_PIN AB24 [get_ports {LA_LPC_P[13]}]
set_property PACKAGE_PIN AC25 [get_ports {LA_LPC_N[13]}]
set_property PACKAGE_PIN AA20 [get_ports {LA_LPC_P[12]}]
set_property PACKAGE_PIN AB20 [get_ports {LA_LPC_N[12]}]
set_property PACKAGE_PIN AE25 [get_ports {LA_LPC_P[11]}]
set_property PACKAGE_PIN AF25 [get_ports {LA_LPC_N[11]}]
set_property PACKAGE_PIN AJ24 [get_ports {LA_LPC_P[10]}]
set_property PACKAGE_PIN AK25 [get_ports {LA_LPC_N[10]}]
set_property PACKAGE_PIN AK23 [get_ports {LA_LPC_P[9]}]
set_property PACKAGE_PIN AK24 [get_ports {LA_LPC_N[9]}]
set_property PACKAGE_PIN AJ22 [get_ports {LA_LPC_P[8]}]
set_property PACKAGE_PIN AJ23 [get_ports {LA_LPC_N[8]}]
set_property PACKAGE_PIN AG25 [get_ports {LA_LPC_P[7]}]
set_property PACKAGE_PIN AH25 [get_ports {LA_LPC_N[7]}]
set_property PACKAGE_PIN AK20 [get_ports {LA_LPC_P[6]}]
set_property PACKAGE_PIN AK21 [get_ports {LA_LPC_N[6]}]
set_property PACKAGE_PIN AG22 [get_ports {LA_LPC_P[5]}]
set_property PACKAGE_PIN AH22 [get_ports {LA_LPC_N[5]}]
set_property PACKAGE_PIN AH21 [get_ports {LA_LPC_P[4]}]
set_property PACKAGE_PIN AJ21 [get_ports {LA_LPC_N[4]}]
set_property PACKAGE_PIN AG20 [get_ports {LA_LPC_P[3]}]
set_property PACKAGE_PIN AH20 [get_ports {LA_LPC_N[3]}]
set_property PACKAGE_PIN AF20 [get_ports {LA_LPC_P[2]}]
set_property PACKAGE_PIN AF21 [get_ports {LA_LPC_N[2]}]
set_property PACKAGE_PIN AE23 [get_ports {LA_LPC_P[1]}]
set_property PACKAGE_PIN AF23 [get_ports {LA_LPC_N[1]}]
set_property PACKAGE_PIN AD23 [get_ports {LA_LPC_P[0]}]
set_property PACKAGE_PIN AE24 [get_ports {LA_LPC_N[0]}]


set_property IOSTANDARD LVCMOS15 [get_ports {SW_DEBUG[0]}]
set_property IOSTANDARD LVCMOS15 [get_ports {SW_DEBUG[1]}]

set_property PACKAGE_PIN AG5  [get_ports {SW_DEBUG[0]}]
set_property PACKAGE_PIN AB12 [get_ports {SW_DEBUG[1]}]

#set_property PACKAGE_PIN D21 [get_ports {FMC_DEBUGOUT_P[0]}]
#set_property PACKAGE_PIN C21 [get_ports {FMC_DEBUGOUT_N[0]}]
#set_property PACKAGE_PIN H21 [get_ports {FMC_DEBUGOUT_P[1]}]
#set_property PACKAGE_PIN H22 [get_ports {FMC_DEBUGOUT_N[1]}]

create_clock -period 5.000 -name CLK_200M -waveform {0.000 2.500} -add [get_nets CLK_200M]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets CLK_200M]

create_clock -period 10.000  -name CLK_100M -waveform {0.000 5.000}  -add [get_nets CLK_100M]
create_clock -period 100.000 -name CLK_10M  -waveform {0.000 50.000} -add [get_nets CLK_10M]
