# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nakazawa/8-gev/kc705/firmware/extinction.srcs/sources_1/ip/bram_2byte_2K/bram_2byte_2K.xci
# IP: The module: 'bram_2byte_2K' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nakazawa/8-gev/kc705/firmware/extinction.srcs/sources_1/ip/bram_2byte_2K/bram_2byte_2K_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_2byte_2K'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/nakazawa/8-gev/kc705/firmware/extinction.srcs/sources_1/ip/bram_2byte_2K/bram_2byte_2K.xci
# IP: The module: 'bram_2byte_2K' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nakazawa/8-gev/kc705/firmware/extinction.srcs/sources_1/ip/bram_2byte_2K/bram_2byte_2K_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_2byte_2K'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
